### ISSUE TITLE
UnboundLocalError: local variable 'atime' referenced before assignment

### ISSUE THREAD

**Issue by farfromsubtle** [jthickstun/anticipation#1]
Been using anticipation quite a lot in the last couple says and I have found that this error inevitably comes up while generating longer pieces (60-90 seconds)

UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-62-cdf83e0d2096>](https://2p83uazrjau-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230614-060133-RC01_540321000#) in <cell line: 7>()
      5 n = 10
      6 
----> 7 proposal = generate(model, start_time=length, end_time=length+n, inputs=history, top_p=0.98)
      8 Audio(synthesize(fs, proposal))

[/usr/local/lib/python3.10/dist-packages/anticipation/sample.py](https://2p83uazrjau-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230614-060133-RC01_540321000#) in generate(model, start_time, end_time, inputs, controls, top_p, debug, delta)
    158         while True:
    159             while current_time >= anticipated_time - delta:
--> 160                 tokens.extend([atime, adur, anote])
    161                 if debug:
    162                     note = anote - ANOTE_OFFSET

UnboundLocalError: local variable 'atime' referenced before assignment

**Comment by jthickstun** [comment]
Thanks for catching this!

It should be resolved by 70da95e.

I was using the wrong concept of a "maximum time" when checking if there are more notes to anticipated. I had used MAX_TIME, which is the maximum time within a Transformer sequence buffer, when I should have been using math.inf for which we always have time < math.inf.
